version: '3'
services:

  #PHP Service
  app:
    image: php:7.4-fpm
    container_name: ${APP_NAME}-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src/:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini    
    networks:
      - ${APP_NAME}-app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: ${APP_NAME}-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/      
    networks:
      - ${APP_NAME}-app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: ${APP_NAME}-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD_ROOT
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD     
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf   
    networks:
      - ${APP_NAME}-app-network

#Docker Networks
networks:
  laboratorio-app-network:
    driver: bridge

#Docker Volumes
volumes:
  dbdata:
    driver: local    